name: x_analysis
description: Recommended lints
version: 0.0.6

repository:
  type: git
  url: https://github.com/peyman93/x_analyze

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_code_metrics: 5.7.5
